### ISSUE TITLE
Strain energy ignored in computation?

### ISSUE THREAD

**Issue by sharma-n** [sgsellan/fracture-modes#2]
Hi @sgsellan,
This is pretty cool stuff! thanks for putting it up on github :)
I was looking at the `compute_fracture_modes()` function and realized that the call to `conic_solve` does not include the hessian $Q$ that you compute earlier in the code. It only takes in the `discontinuity matrix`. Could you help me understand what the `discontinuity matrix` is? And the fact that $Q$ is not being passed to the solver, does that mean that you ignore the strain energy when computing the modes?

Looking forward to your answer!

**Comment by sgsellan** [comment]
Hi!

Thanks for the kind words! Indeed, our published code uses the efficient implementation as described in appendix B of [our paper](https://www.silviasellan.com/pdf/papers/fracture-harmonics.pdf) where the system is reduced and the zero strain energy is added as a constraint to the system instead of a quadratic term in the energy. Let me know if you have any more questions!

**Comment by sharma-n** [comment]
Ah got it. Thanks for the quick response!
